### PR TITLE
feat(valdrService, valdrFormItem): Add possibility to reference whole fo...

### PR DESCRIPTION
**Pull request by luaks**
...rm in validator

Add formValues as parameter for validate function.
Add equaldField validator to check if fields are equal, for example when checking a password when creating a user account

### CODE REVIEW

**Comment by derLukers** [comment]
I'll try to raise this back to 100% tomorrow ;-)

**Comment by philippd** [comment]
Thanks for the pull request @luaks 

I like the idea of having access to all form values in the validators. It was also requested in https://github.com/netceteragroup/valdr/issues/68

The problem with this approach is that ```setValue``` is only called in the revalidate event handler. This event is only fired when the constraints change and the values stored in the ```valdrType```directive will therefore not always be up to date.

In general I would prefer a solution which reads the values from the ```ngForm``` directly instead of storing them in one of the valdr directives.

**Comment by luaks** [comment]
It would be great to have it that way indeed, but I can't seem to find any way to access the form data via `ngForm` since the data never passes through `ngForm` but is only set to the model via ng-Model.

I have put the update into the `validate` function of the `valdrFormItem` directive, just before the call to valdr validate, to make sure it gets called before any validation.

**Comment by luaks** [comment]
@marcelstoer @philippd could you have another look over this?
I have solved the problems indicated by @philippd regarding the model values and I think now there should not be any problems regarding race conditions.

**Comment by philippd** [comment]
@luaks sorry for the late reply, we'll have a look at it again and get back to you soon

**Comment by B8li** [comment]
Hi @luaks and @philippd,

Sorry for my late response.
I checked and tested PR and code look fine. I have one remark:
 - We only have access to values within same valdr type. If we have example where we have Person and inside that object we have Adress, then we can not access fields from Adress when we are validating Person. Also if we have nested form controllers (ng-form) then we have problem accessing values from parent form or it's sibling form.

In my opinion. we should be able to access all form elements if we want to make such custom validation. I would go in direction to somehow create wrapping directive that will expose values from it's children form/forms to valdr.

@philippd do you think that we should consider case with multiple forms and nested forms for validation or should we say that validation will work per form?

**Comment by philippd** [comment]
I'm sorry @luaks, but after a long discussion with @B8li we came to the conclusion that we will not merge this pull request. The main issue is that it will not work in all situations that valdr supports. Especially if you have nested forms and mixed ```valdr-types``` in them. Collecting all values in the ```valdr-type``` also adds a (small) unneeded overhead for most cases. We will continue to focus on doing single field validation really well and for now not add any cross field validation logic. 

Thanks anyway for your pull request. If we find a way to easily access all field values of a ```valdr-type``` in a form, we can discuss this again.

**Pull request closed without merging**
