### PR TITLE
hibernateEmailValidator: also return 'true' for NaN input

### PR DESCRIPTION
**Pull request by Arzie**
Ran into this in our project, where the input was NaN at some time.

### CODE REVIEW

**Comment by philippd** [comment]
I think this should only happen if you have an input of type number as your e-mail input field. Which actually does not make sense at all. :) Can you give some details about how you got NaN there?

**Comment by Arzie** [comment]
Thanks for your reply!

Agreed on the type="number" ;-). In our case, the type="email" (hardcoded), so that shouldn't be the cause.

The problem does not occur when we directly open the URL where the form is located(http://localhost:8000/ui/#/user/register).

The problem only happens when we switch from another state to the state with the form (i.e., browse to http://localhost:8000/ui/#/user/login and click 'create user', which navigates to http://localhost:8000/ui/#/user/register).

We're using Angular, angular-ui-router, TypeScript and valdr. I saw it happen both in Chrome and Firefox.

Any ideas?

**Comment by Arzie** [comment]
Any updates on this?

**Comment by marcelstoer** [comment]
@philippd I'd like to close this as we seem to agree that number types for email input fields is not a legit use case. The real issue appears to be unrelated to valdr and should be handled as a [support request](https://github.com/netceteragroup/valdr#support). Agree?

**Comment by Arzie** [comment]
Go ahead Marcel, the value should never become NaN and if it does, the cause lies somewhere else.

**Pull request closed without merging**
